import { Translate } from '../interfaces/translate';

export function getTranslateEn(): Translate {
  return {
    user: {
      roleSelect: 'Select role / none role',
      roleEmployee: 'Employee role',
      roleAdmin: 'Administrator role',
      firstRole: 'First role:',
      secondRole: 'Second role:',
      enabled: 'Enabled / Disabled',
      firstName: 'First name:',
      lastName: 'Last name:',
      phone: 'Phone:',
      language: 'Select language',
      image: 'Select image',
      successSubject: 'Success!',
      success_add_msg: 'User has been added to database. We sent email on entered address with confirmation include login and auto genereted password. If user was added on registration page, email include alseo activation link.',
      successUpdate: 'User data has been updated with success.',
      companyName: 'Company name:',
      zipCode: 'Zip code:',
      city: 'City:',
      street: 'Street:',
      streetNo: 'Street No',
      unitNo: 'Unit No',
      latitude: 'Latitude:',
      longitude: 'Longitude:',
      gender: 'Gender:',
      male: 'Male',
      female: 'Female',
      country: 'Country:',
      registerDateTime: 'Registered date time:',
      editDateTime: 'Last modified date time:',
      searchPatient: 'Search patient:',
      confirmRemove: 'Are you sure you want to remove?',
      successRemove: 'Patient account has been removed from application with success.',
      removePatientAccount: 'Remove my account',
      removePatientInfo: 'If You want remove your account, you can use option below. After this Your account will be remove today 1 hour from now. On Your email address will be send confirmation.',
      cancelRemovePatientAccount: 'Cancel remove my account',
      cancelRemovePatientInfo: 'If You want cancel your order to remove account, you can use option below. After this your order to remove account will be cancel now. On Your email address will be send confirmation.',
      doctorExperience: 'Professional experience:',
      orderRemovePatient: 'Order remove your patient account has been registered with success.',
      cancelOrderRemovePatient: 'Success canceled order remove your patient account.',
      greeting: 'Welcome ',
      registerSocialUser: 'For proprely working our application, we need your data. Pleas complete form below and save. We will send to you email with notification of new account data.',
      workingHour: 'Working hours',
      doesNotWork: 'Does not work'
    },
    button: {
      select: 'Select',
      save: 'Save data',
      update: 'Update user data',
      delete: 'Delete',
      search: 'Search',
      removePatient: 'Remove patient',
      register: 'Register',
      schedule: 'Schedule visit',
      nextWeek: 'Next week',
      previousWeek: 'Previous week',
      details: 'Details',
      confirm: 'Visit confirmation',
      diagnosis: 'Make a diagnosis',
      addReferral: 'Add referral',
      createPdf: 'Create pdf',
      deletePhoto: 'Delete photo'
    },
    login: {
      password: 'Password:',
      passwordRepet: 'Repet password:',
      resetPassword: 'Reset password only',
      success_reset_pass: 'Password has been reseted with success.',
      signin: 'Sign in',
      recover: 'Recover password',
      recoverPassPlaceholder: 'If you forgot password click this button:',
      recoverPassDescription: 'If your account is active, pleas enter data to below form. After correct verification you will get email with link to reset your password. New password will send by next email.',
      recoverPassSentEmail: 'Email with link to reset password has been sent on your email',
      resetPasswordPage: 'Reset password page',
      logoutDifferentUsername: 'Your username has been change therefore you must logout. Do you agree logout?',
      google: 'Sign in with google:',
      facebook: 'Sign in with facebook:',
      register: 'If You not yet account in our service, pleas register:'
    },
    menu: {
      owner: 'Owner',
      admin: 'Administrator',
      doctor: 'Doctor',
      employee: 'Employee',
      patient: 'Patient',
      home: 'Home',
      agenda: 'Agenda',
      contactus: 'Contact Us',
      signin: 'Sign in',
      logged: 'Logged as: ',
      logout: 'Logout',
      addAdmin: 'Add administrator',
      updateAdmin: 'Update administrator',
      selfUpdate: 'Update my own data',
      removeMyAccount: 'Remove my account',
      addEmployee: 'Add employee',
      updateEmployee: 'Update employee data',
      addDoctor: 'Add doctor',
      updateDoctor: 'Update doctor data',
      addPatient: 'Add patient',
      updatePatient: 'Update patient data',
      removePatient: 'Remove patient account',
      selfEditAgenda: 'Update my agenda',
      scheduleVisit: 'Schedule visit',
      cancelVisit: 'Cancel oncoming visit',
      doctorFreeDays: 'Doctor free days',
      clinicFreeDays: 'Clinic free days',
      updateDoctorAgenda: 'Update doctor agenda',
      myVisits: 'My visits',
      patientVisits: 'Patient visits',
      visitConfirmation: 'Visit confirmation',
      myPlannedVisits: 'My planned visits',
      makeDiagnosis: 'Make the diagnosis',
      medicalDocumentation: 'Medical documentation',
      selfSetFreeDays: 'Set my free days'
    },
    header: {
      greeting: 'Welcome in Medical Clinic',
      doctorPhone: 'Doctor, phone',
      patientPhone: 'Patient, phone',
      patientAilments: 'Patient ailments',
      visitStatus: 'Visit ststus',
      patientPhoto: 'Patient photo',
      referrals: 'Referrals to additional medical examination:',
      recognition: 'Medical recognition:',
      researchUnit: 'Research unit:',
      scopeOfExam: 'Scope of examination:',
      disgnosisAndOrders: 'DIAGNOSIS AND DOCTOR ORDERS FOR PATIENT',
      referralToExam: 'REFERRAL TO MEDICAL EXAMINATION',
      address: 'Address:',
      visitDate: 'Visit date',
      visitTime: 'Visit time',
      oncomingVisitList: 'ONCOMING VISITS LIST',
      visitDateRange: 'Visit date range:',
      photo: 'Photo',
      description: 'Description',
      enabled: 'Shared',
      medicalDocNotFound: 'Medical documentation not found.',
      medicalDocumentation: 'Patient medical documentation:'
    },
    home: {
      description: 'Short description of how Medical Clinic works',
      msgSubject: 'Message subject:',
      msgContent: 'Message content:',
      emailReply: 'Email to reply:',
      selectFiles: 'Select files',
      sendEmail: 'Send email',
      confirmSentMail: 'Mail has ben sent correctly.',
      reCaptcha: 'ReCaptcha verifying:',
      fileName: 'File name',
      fileType: 'File type',
      fileSize: 'File size(B)',
      filesClear: 'Clear all files',
      activationPatientPage: 'Activation patient page.',
      successActivationPatient: 'Activation process has been ended with success. You can login now.',
      monday: 'Monday',
      tuesday: 'Tuesday',
      wednesday: 'Wednesday',
      thursday: 'Thursday',
      friday: 'Friday',
      saturday: 'Saturday',
      sunday: 'Sunday'
    },
    visit: {
      scheduled: 'Visit has been scheduled with success. We sent email with confirmation.',
      addClinicFreeDay: 'Add free day for clinic:',
      addDoctorFreeDay: 'Add free day for doctor:',
      freeDay: 'Free day',
      freeDayRemoved: 'Selected day has been removed.',
      agenda: 'Agenda - select doctor to check his free visit terms:',
      freeTerm: 'free',
      takenTerm: 'taken',
      selectDoctor: 'Select doctor to schedule visit:',
      visitDateTime: 'Visit date, time',
      ailmentDiagnosedDoctor: 'Ailment diagnosed by doctor:',
      patientAilmentsInfo: 'Ailments registered to schedule visit (optional):',
      diagnosis: 'Diagnosis:',
      deleted: 'Visit term has been canceled.',
      details: 'Visit detals:',
      reservation: 'Reservation date',
      selectedPatient: 'Selected patient:',
      visitStatus: 'Visit status',
      reservationByEmployee: 'Reserved by employee',
      reservationByPatient: 'Reserved by patient',
      confirmed: 'Visit status has been changed on: CONFIRMED.',
      orders: 'Doctor orders:',
      medicines: 'Prescribed medicines and dosage:',
      makedDiagnosis: 'Diagnosis has been maked with success.',
      updateMedicalDocum: 'Medical documentation has been updated with success.',
      statusPlanned: 'Planned',
      statusConfirmed: 'Confirmed',
      statusCompleted: 'Completed'
    },
    error: {
      requiredField: 'Field must be matches with user instruction if is mandatory. ',
      oryginalPhotoSize: 'Oryginal file size is too big. Max file byte size is ',
      compressedPhotoSize: 'Compressed file size is too big. Max file byte size is ',
      language: 'Select language is necessary',
      subject: 'Defeat!',
      not_unique: 'Entered login/email is not unique. Pleas enter other login/email.',
      invalid: 'Server answered that entered data are invalid. Pleas contact with administrator.',
      no_connect: 'Error connection with server. Check internet connection.',
      err_400: 'Bad HTTP request.',
      err_401: 'Login or password are not correct or user is not enabled.',
      err_403: 'You are not authorized to perform this operation.',
      err_404: 'Resource not found.',
      err_423: 'Resource already exist',
      err_500: 'Internal server error. Pleas contact with administrator.',
      theSameRole: 'Both role can\'t be the same. Pleas change one.',
      none: 'Resource not found.',
      differentPasswords: 'Both password fields are not the same.',
      exceedFileNumber: 'Allowed file number has been exceeded. Maximum number is: ',
      exceedAllFilesSize: 'Allowed size of all files has been exceeded. Maximum byte size is: ',
      recoverPassUserUnknown: 'Entered data are not correct. Send email with link to reset password has been failed.',
      recoverPassDeleyed: 'Time out for reset password use this link. Pleas do new procedure to reset password.',
      gender: 'Gender comes from Pesel. Pleas enter correct Pesel.',
      activationPatient: 'Activation process failed. Pleas contact with administrator.',
      orderRemovePatient: 'Error order remove your patient account. Pleas contact with administrator.',
      orderRemovePatientExist: 'Order remove your patient account already exist.',
      cancelOrderRemovePatient: 'Error cancel order remove your patient account. Pleas contact with administrator.',
      cancelOrderRemovePatientMail: 'Error send email with notification at canceled your patient account.',
      orderRemovePatientNotExist: 'Order remove your patient account not exist.',
      reCaptcha: 'ReCaptcha verifying has been failed.',
      patientNotEnabled: 'Your patient account connected with PESEL number is not enable. Pleas contact with administrator.',
      patientAccountExist: 'Your patient account connected with PESEL number already exist. Pleas login or contact with administrator.',
      patientNotEnabledAdmin: 'Patient account connected with PESEL number is not enable.',
      patientAccountExistAdmin: 'Patient account connected with PESEL number already exist.',
      visitTermTaken: 'Entered visit term is taken.',
      visitDateTimeEmpty: 'Pleas, select date and time visit.',
      pastDate: 'Selected date is past date',
      notFoundVisit: 'Visit not found.'
    }
  };
}

export function getTranslatePl(): Translate {
  return {
    user: {
      roleSelect: 'Wybierz rolę / żadna rola',
      roleEmployee: 'Rola pracownika',
      roleAdmin: 'Rola administratora',
      firstRole: 'First role:',
      secondRole: 'Second role:',
      enabled: 'Aktywny / Nie aktywny',
      firstName: 'Imię:',
      lastName: 'Nazwisko:',
      phone: 'Telefon:',
      language: 'Wybierz język:',
      image: 'Wybierz zdjęcie',
      successSubject: 'Sukces!',
      success_add_msg: 'Użytkownik został dodany do bazy danych. Na podany adres wysłaliśmy email z potwierdzeniem zawierający login i hasło wygenerowane automatycznie. Jeżeli użytkownik został dodany przez stronę rejestracji, mail zawiera także link aktywacyjny.',
      successUpdate: 'Dane użytkownika zostały zaktualizowane z powodzeniem.',
      companyName: 'Nazwa firmy:',
      zipCode: 'Kod pocztowy:',
      city: 'Miasto:',
      street: 'Ulica:',
      streetNo: 'Nr domu:',
      unitNo: 'Nr lokalu',
      latitude: 'Szerokośc geograficzna:',
      longitude: 'Długość geograficzna:',
      gender: 'Płeć:',
      male: 'Mężczyzna',
      female: 'Kobieta',
      country: 'Kraj:',
      registerDateTime: 'Data i czas rejestracji:',
      editDateTime: 'Data i czas ostatniej modyfikacji:',
      searchPatient: 'Wyszukaj pacjenta:',
      confirmRemove: 'Jesteś pewien, że chcesz usunąć?',
      successRemove: 'Konto pacjenta zostało z powodzeniem usunięte z aplikacji.',
      removePatientAccount: 'Usuń moje konto',
      removePatientInfo: 'Jeżeli chcesz usunąć swoje konto, możesz użyć opcji poniżej. Po wybraniu tej opcji, Twoje konto zostanie usunięte po upływie 1 godziny. Na twój adres email zostanie wysłane potwierdzenie.',
      cancelRemovePatientAccount: 'Odwołaj usunięcie mojego konta',
      cancelRemovePatientInfo: 'Jeżeli chcesz anulować zlecenie usunięcia swojego konta, możesz użyć poniższej opcji. Po wybraniu tej opcji zlecenie usunięcia Twojego konta zostanie od razu anulowane. Na Twój adres email zostanie wysłane potwierdzenie.',
      doctorExperience: 'Doświadczenie zawodowe:',
      orderRemovePatient: 'Zlecenie usunięcia twojego konta pacjenta zostało zarejestrowane z powodzeniem.',
      cancelOrderRemovePatient: 'Zlecenie usunięcia twojego konta pacjenta zostało anulowane.',
      greeting: 'Dzień dobry ',
      registerSocialUser: 'Dla poprawnego działania naszej aplikacji potrzebne są twoje dane. Proszę wypełnij poniższy formularz i zapisz. Wyślemy do ciebie email z powiadomieniem o danych nowego konta.',
      workingHour: 'Gpdziny pracy',
      doesNotWork: 'Nie pracuje'
    },
    button: {
      select: 'Wybierz',
      save: 'Zapisz dane',
      update: 'Aktualizuj dane',
      delete: 'Usuń',
      search: 'Wyszukaj',
      removePatient: 'Usuń pacjenta',
      register: 'Zarejestruj',
      schedule: 'Zaplanuj wizytę',
      nextWeek: 'Następny tydzień',
      previousWeek: 'Poprzedni tydzień',
      details: 'Szczegóły',
      confirm: 'Potwierdzenie wizyty',
      diagnosis: 'Wystaw diagnozę',
      addReferral: 'Dodaj skierowanie',
      createPdf: 'Utwórz pdf',
      deletePhoto: 'Usuń zdjęcie'
    },
    login: {
      password: 'Hasło:',
      passwordRepet: 'Powtórz hasło:',
      resetPassword: 'Tylko reset hasła',
      success_reset_pass: 'Hasło zostało zresetowane z powodzeniem.',
      signin: 'Zaloguj się',
      recover: 'Odzyskaj hasło',
      recoverPassPlaceholder: 'Jeżeli hasło zostało zapomniane, proszę kliknij ten przycisk:',
      recoverPassDescription: 'Jeżeli twoje konto jest aktywne, proszę wprowadź dane do poniższego formularza. Po poprawnej weryfikacji otrzymasz email z linkiem do resetu twojego hasła. Nowe hasło zostanie wysłane następnym mailem.',
      recoverPassSentEmail: 'Email z linkiem do resetu hasła został wysłany na Twój email.',
      resetPasswordPage: 'Strona resetowania hasła',
      logoutDifferentUsername: 'Twój login został zmieniony w związku z czym musisz zostać wylogowany. Zgadzasz się na wylogowanie',
      google: 'Zaloguj się przez google:',
      facebook: 'Zaloguj się przez facebook:',
      register: 'Jeżeli jeszcze nie masz konta w naszym serwisie, zarejestruj się:'
    },
    menu: {
      owner: 'Właściciel',
      admin: 'Administrator',
      doctor: 'Lekarz',
      employee: 'Pracownik',
      patient: 'Pacjent',
      home: 'Strona główna',
      agenda: 'Terminarz',
      contactus: 'Kontakt',
      signin: 'Logowanie',
      logged: 'Zalogowany jako: ',
      logout: 'Wyloguj',
      addAdmin: 'Dodaj administratora',
      updateAdmin: 'Aktualizuj dane administratora',
      selfUpdate: 'Aktualizuj własne dane',
      removeMyAccount: 'Usuń moje konto',
      addEmployee: 'Dodaj pracownika',
      updateEmployee: 'Aktualizuj dane pracownika',
      addDoctor: 'Dodaj lekarza',
      updateDoctor: 'Aktualizuj dane lekarza',
      addPatient: 'Dodaj pacjenta',
      updatePatient: 'Aktualizuj dane pacjenta',
      removePatient: 'Usuń konto pacjenta',
      selfEditAgenda: 'Aktualizuj mój terminarz',
      scheduleVisit: 'Zaplanuj wizytę',
      cancelVisit: 'Anuluj nadchodzącą wizytę',
      doctorFreeDays: 'Wolne dni lekarza',
      clinicFreeDays: 'Wolne dni przychodni',
      updateDoctorAgenda: 'Aktualizuj terminarz lekarza',
      myVisits: 'Moje wizyty',
      patientVisits: 'Wizyty pacjenta',
      visitConfirmation: 'Potwierdzenie wizyty',
      myPlannedVisits: 'Moje zaplanowane wizyty',
      makeDiagnosis: 'Wystaw diagnozę',
      medicalDocumentation: 'Documentacja medyczna',
      selfSetFreeDays: 'Ustalenie dni wolnych'
    },
    header: {
      greeting: 'Zapraszamy do przychodni lekarskiej',
      doctorPhone: 'Lekarz, tel.',
      patientPhone: 'Pacjent, tel.',
      patientAilments: 'Dolegliwości pacjenta',
      visitStatus: 'Status wizyty',
      patientPhoto: 'Patient photo',
      referrals: 'Skierowania na dodatkowe badania:',
      recognition: 'Rpzpoznanie:',
      researchUnit: 'Pracownia badawcza:',
      scopeOfExam: 'Zakres badania:',
      disgnosisAndOrders: 'DIAGNOZA I ZALECENIA DLA PACJENTA',
      referralToExam: 'SKIEROWANIE NA BADANIA MEDYCZNE',
      address: 'Adres:',
      visitDate: 'Data wizyty',
      visitTime: 'Godz. wizyty',
      oncomingVisitList: 'LISTA NADCHODZĄCYCH WIZYT',
      visitDateRange: 'Wizyty w datach:',
      photo: 'Zdjęcie',
      description: 'Opis',
      enabled: 'Udostę-pniony',
      medicalDocNotFound: 'Nie znaloziono dokumentacji medycznej.',
      medicalDocumentation: 'Dokumentacja medyczna pacjenta:'
    },
    home: {
      description: 'Krótki opis prowadzonej działalności medycznej.',
      msgSubject: 'Temat wiadomości:',
      msgContent: 'Treść wiadomości:',
      emailReply: 'Email do odpowiedzi:',
      selectFiles: 'Wybierz pliki',
      sendEmail: 'Wyślij email',
      confirmSentMail: 'Mail został wysłany prawidłowo.',
      reCaptcha: 'Weryfikacja ReCaptcha:',
      fileName: 'Nazwa pliku',
      fileType: 'Typ pliku',
      fileSize: 'Rozmiar pliku(B)',
      filesClear: 'Wyczyść wszystkie pliki',
      activationPatientPage: 'Strona aktywowania pacjenta.',
      successActivationPatient: 'Proces aktywacji konta pacjenta zakończony powodzeniem. Możesz się teraz zalogować.',
      monday: 'Poniedziałek',
      tuesday: 'Wtorek',
      wednesday: 'Środa',
      thursday: 'Czwartek',
      friday: 'Piątek',
      saturday: 'Sobota',
      sunday: 'Niedziela'
    },
    visit: {
      scheduled: 'Wizyta została zaplanowana z powodzeniem. Wysłaliśmy email z potwierdzeniem',
      addClinicFreeDay: 'Dodaj dzień wolny dla przychodni:',
      addDoctorFreeDay: 'Dodaj dzień wolny dla lekarza:',
      freeDay: 'Dzień wolny',
      freeDayRemoved: 'Wybrany dzień został usunięty',
      agenda: 'Terminarz - wybierz lekarza aby sprawdzić jego wolne terminy wizyt:',
      freeTerm: 'wolna',
      takenTerm: 'zajęta',
      selectDoctor: 'Wybierz lekarza w celu umówienia wizyty:',
      visitDateTime: 'Data i czas wizyty',
      ailmentDiagnosedDoctor: 'Dolegliwości zdiagnozowane przez lekarza:',
      patientAilmentsInfo: 'Dolegliwości zgłaszane przy rejestracji (opcjonalnie):',
      diagnosis: 'Diagnoza:',
      deleted: 'Termin wizyty został anulowany.',
      details: 'Szczegóły wizyty:',
      reservation: 'Data rezerwacji',
      selectedPatient: 'Wybrany pacjent:',
      visitStatus: 'Staus wizyty',
      reservationByEmployee: 'Zarezerwowano przez pracownika',
      reservationByPatient: 'Zarezerwowano przez pacjenta',
      confirmed: 'Status wizyty został zmieniony na: POTWIERDZONA.',
      orders: 'Zalecenia lekarza:',
      medicines: 'Przepisane leki i dawkowanie:',
      makedDiagnosis: 'Diagnoza została wykonana z powodzeniem.',
      updateMedicalDocum: 'Dokumentacja medyczna została zaktualizowana z powodzeniem.',
      statusPlanned: 'Planowana',
      statusConfirmed: 'Potwierdzona',
      statusCompleted: 'Zrealizowana'
    },
    error: {
      requiredField: 'Pole powinno być dopasowane wg instrukcji użytkownika jeżeli jest wymagane. ',
      oryginalPhotoSize: 'Rozmiar oryginalnego pliku jest zbyt duży. Max rozmiar pliku w bajtach to ',
      compressedPhotoSize: 'Rozmiar skompresowanego pliku jest zbyt duży. Max rozmiar pliku w bajtach to ',
      language: 'Wybór języka jest niezbedny',
      subject: 'Niepowodzenie!',
      not_unique: 'Wprowadzony login/email nie jest unikalny. Proszę wprowadź inny login/email.',
      invalid: 'Serwer odpowiedział, iż wprowadzone dane są niepoprawne. Proszę skontaktuj się z administratorem.',
      no_connect: 'Błąd połączenia z serwerem. Sprawdź połączenie z internetem.',
      err_400: 'Błąd żądania HTTP.',
      err_401: 'Login lub hasło są niepoprawne bądź użytkownik jest nieaktywny.',
      err_403: 'Nie masz uprawnień do wykonania tej operacji.',
      err_404: 'Zasób nie został odnaleziony.',
      err_423: 'Zasób już istnieje',
      err_500: 'Wewnętrzny błąd serwera. Proszę skontaktuj się z administratorem.',
      theSameRole: 'Obie role nie mogą być takie same. Proszę zmień jedną z nich.',
      none: 'Nie odnaleziono zasobów.',
      differentPasswords: 'Hasła w obu polach nie są takie same.',
      exceedFileNumber: 'Dozwolona liczba plików została przekroczona. Maksymalna liczba to: ',
      exceedAllFilesSize: 'Dozwolony rozmiar wszystkich plików został przekroczony. Maksymalny rozmiar bajtów to: ',
      recoverPassUserUnknown: 'Wprowadzone dane są niepoprawne. Niepowodzenie w wysyłaniu maila z linkiem do resetu hasła.',
      recoverPassDeleyed: 'Przekroczono czas użycia linku do resetu hasła. Proszę o wykonanie od nowa procedury resetu hasła.',
      gender: 'Płeć pochodzi z numeru Pesel. Proszę wprowadź poprawny Pesel.',
      activationPatient: 'Niepowodzenie procesu aktywacji pacjenta. Proszę o kontakt z administratorem.',
      orderRemovePatient: 'Niepowodzenie zlecenia usunięcia twojego konta pacjenta. Proszę o kontakt z administratorem.',
      orderRemovePatientExist: 'Zlecenie usunięcia twojego konta pacjenta jest już aktywowane.',
      cancelOrderRemovePatient: 'Niepowodzenie odwołania zlecenia usunięcia twojeg konta pacjenta. Proszę o kontakt z administratorem.',
      cancelOrderRemovePatientMail: 'Błąd wysyłki email z powiadomieniem o odwołaniu zlecenia usunięcia twojego konta pacjenta.',
      orderRemovePatientNotExist: 'Zlecenie usunięcia twojego konta pacjenta jeszcze nie zostało aktywowane.',
      reCaptcha: 'Weryfikacja ReCaptcha nie powiodła się.',
      patientNotEnabled: 'Twoje konto pacjenta powiązane z numerem PESEL nie jest aktywne. Proszę o kontakt z administratorem.',
      patientAccountExist: 'Twoje konto pacjenta powiązane z numerem PESEL jest już aktywne. Proszę zaloguj się lub skontaktuj z administratorem.',
      patientNotEnabledAdmin: 'Konto pacjenta powiązane z numerem PESEL nie jest aktywne.',
      patientAccountExistAdmin: 'Konto pacjenta powiązane z numerem PESEL jest już aktywne.',
      visitTermTaken: 'Wprowadzony termin wizyty jest już zajęty.',
      visitDateTimeEmpty: 'Proszę o wybranie daty i czasu wizyty.',
      pastDate: 'Wybrana data jest datą przeszłą',
      notFoundVisit: 'Nie znaleziono wizyt.'
    }
  };
}
